cursor_handle

[ -f $XDG_CONFIG_HOME/X11/Xresources ] && xrdb -load $XDG_CONFIG_HOME/X11/Xresources

xset r rate 200 &
wallpaper &
xcompmgr -c &

# urxvt -geometry 160x45+0+0 -e tmux
exec openbox-session
