"respecting XDG
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo "moves .viminfo to cache

"global settings
let mapleader='\'
set ttyfast
set number
set autoindent
set tabstop=4
set completeopt=menuone,noinsert,noselect
set ignorecase
set incsearch
set secure
colorscheme peachpuff
syntax on

"Section for global nnoremapping
nnoremap ;<Space> /<++><Enter>"_c4l

"Section for global inoremaping
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i
inoremap { {}<Esc>i
inoremap <leader>a <++><Esc>

"Copying and pasting to X11 clip
vnoremap gy :!xclip -i -selection clipboard -f<CR>
nnoremap gp :-1r !xclip -o -selection clipboard -r<CR>

"Section for highlight management
highlight Folded ctermbg=black
highlight MatchParen cterm=bold ctermbg=none ctermfg=darkgreen

"startup and mapping for c
autocmd FileType c setlocal foldmethod=syntax
autocmd BufNewFile *.c 0r ~/.local/skeletons/skeleton.c
