"Annoyingly, I have to put this line here, or some settings that come before it won't work
set nocompatible

"respecting XDG
set runtimepath-=$HOME/.vim
set runtimepath+=$XDG_DATA_HOME/vim
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set directory=$XDG_CACHE_HOME/vim
set backupdir=$XDG_CACHE_HOME/vim

"global settings
let mapleader='\'
set ttyfast
set number
set autoindent
set tabstop=4
set completeopt=menuone,noinsert,noselect
set ignorecase
set incsearch
set secure
set wildmenu
colorscheme peachpuff
syntax on
autocmd FileType * setlocal formatoptions-=cro

"Section for global nnoremapping
nnoremap ;<Space> /<++><Enter>"_c4l
"showing trailing whitespace
nnoremap <leader>wn :match ExtraWhiteSpace /\s\+$/<CR>
nnoremap <leader>wf :match<CR>

"Section for global inoremaping
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i
inoremap { {}<Esc>i
inoremap <leader>a <++><Esc>

"Copying and pasting to wayland clip
vmap gy y:call system("wl-copy --trim-newline", @@)<CR>
nnoremap gp :-1read !wl-paste --no-newline<CR>

"Section for highlight management
highlight Folded ctermbg=black
highlight ExtraWhiteSpace ctermbg=red
highlight MatchParen cterm=bold ctermbg=none ctermfg=darkgreen

"Finding files
set path+=**
let g:netrw_banner=0

".ms files
autocmd Filetype nroff set foldmethod=marker
